-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: a11d9314b22d8f8c7556443875b731ef05965464
    hooks:
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E501
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: flake8
        args:
        - --max-line-length=255
    -   id: trailing-whitespace
-   repo: git://github.com/ivanlei/pre-commit-python-sorter
    sha: 24081074f3ce0768fef74b518cb76333fb03c650
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
        - --force_single_line
